config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :products do
    resources :reviews, only: [:new, :create]
  end

  get '/login'  =>  'sessions#new', as: 'login'
  post '/login' =>  'sessions#create'
  delete '/logout' => 'sessions#destroy', as: 'logout'
  resources :merchants, only: [:new, :create, :show] do
    get :dashboard
    resources :products
    resources :orders, only: [:index, :show]

  end

  resources :categories, only: [:new, :create, :show]

  resources :orders, only: [:edit, :update, :show]

  get 'orders/:id/estimate', to: 'orders#estimate', as: "estimate"
  post 'orders/:id/results', to: 'orders#results', as: "results"
  post 'orders/:id/create-estimate', to:'orders#create_estimate', as: 'create-estimate'
  get 'orders/:id/confirmation', to: 'orders#confirmation', as: 'order_confirmation'
  get 'merchant/:merchant_id/orders/shipped' => 'orders#shipped', as: "orders_shipped"
  get 'merchant/:merchant_id/orders/unshipped' => 'orders#unshipped', as: "orders_unshipped"

  patch 'merchants/:merchant_id/products/:id/active_update' => 'products#active_update', as: "active_update"

  patch 'merchants/:merchant_id/order_items/:id' => 'order_items#mark_shipped', as: "mark_shipped"

  get '/cart'             =>  'carts#show'
  post '/add_to_cart/:id' =>  'carts#add_to_cart', as: 'add_to_cart'

  resources :order_items

end

app/models/order.rb
class Order < ActiveRecord::Base
  # Associations
  has_many :order_items
  has_many :products, :through => :order_items
end

app/controllers/orders_controller.rb
require 'httparty'

class OrdersController < ApplicationController
  before_action :require_login, except: [:estimate, :results, :edit, :update, :confirmation, :create_estimate]

  def index
    if session[:merchant_id] == params[:merchant_id].to_i
      @merchant = Merchant.find(params[:merchant_id])

      # find only orders that are complete
      @orders = @merchant.orders.where(status: "complete").uniq.reverse

      @order_items = find_relevant_order_items(@orders, @merchant.id)

      # from completed orders, find order items that belong to this merchant
      # sum up the revenue from these order items
      @shipped_revenue = revenue(@order_items, true)
      @unshipped_revenue = revenue(@order_items, false)
      @shipped_count = count_items(@order_items, true)
      @unshipped_count = count_items(@order_items, false)

    else
      flash[:error] = "You do not have access to that merchant's orders."

      redirect_to merchant_dashboard_path(session[:merchant_id])
    end
  end

  def estimate
    @order_items = current_order.order_items
    calc_order_total
    @order = current_order
    @total_weight = 0
    @package_size = []
    @order.products.each do |product|
      @total_weight += product.weight
      @package_size << product.box_size
    end
    if @package_size.include?("large")
      @package_size = "large"
    elsif @package_size.include?("medium")
      @package_size = "medium"
    else
      @package_size = "small"
    end

  end

  def results
    @order = Order.find(params[:id])
    @estimate = params["estimate"]
    @order.update!(name: @estimate["name"], email: @estimate["email"], street: @estimate["street"], city: @estimate["city"], state: @estimate["state"], zip: @estimate["zip"])
    @order_items = current_order.order_items
    @shipment_response = HTTParty.get("http://shipyostuff.herokuapp.com/", :body => @estimate)
    # for heroku: http://shipyostuff.herokuapp.com/
    # for localhost: http://localhost:3001/
    if @shipment_response.include?("message")
      flash[:error] = @shipment_response["message"]
      redirect_to estimate_path
    else
      @usps = @shipment_response[1]
      @ups = @shipment_response[0]
      calc_order_total
    end

  end

  def create_estimate
    @estimate = JSON.parse(params["service_info"]["estimate"])
    @order_items = current_order.order_items
    calc_order_total
    # @order_with_shipping = calc_order_total + @shipping_price
    @order = Order.find(params[:id])
    edit
    render :edit
  end

  def calc_order_total
    @order_total = 0

    @order_items.each do |order_item|
      @order_total += order_item.revenue
    end

    return @order_total
  end

  def shipped
    @merchant = Merchant.find(params[:merchant_id])
    @orders = @merchant.orders.where(status: "complete").uniq.reverse
    @order_items = find_relevant_order_items(@orders, @merchant.id)
    @order_items_shipped = shipped?(@order_items, true)

    @shipped_orders = find_orders_by_status(@orders, true, @merchant.id)

    @shipped_revenue = revenue(@order_items, true)
    @unshipped_revenue = revenue(@order_items, false)
    @shipped_count = count_items(@order_items, true)
    @unshipped_count = count_items(@order_items, false)

  end

  def unshipped
    @merchant = Merchant.find(params[:merchant_id])
    @orders = @merchant.orders.where(status: "complete").uniq.reverse
    @order_items = find_relevant_order_items(@orders, @merchant.id)
    @order_items_unshipped = shipped?(@order_items, false)

    @unshipped_orders = find_orders_by_status(@orders, false, @merchant.id)

    @shipped_revenue = revenue(@order_items, true)
    @unshipped_revenue = revenue(@order_items, false)
    @shipped_count = count_items(@order_items, true)
    @unshipped_count = count_items(@order_items, false)
  end

  def show
    # a merchant can view a particular order and all of its details (i.e. order_items/totals, etc.)
    @order = Order.find(params[:id])

    @order_items = Merchant.find(params[:merchant_id]).order_items

    @redacted_cc = redacted_cc(@order.credit_card)
  end

  def edit
    # every time a new order_item is added/removed from the cart
    # when the customer adds their payment details
    # params[:id] is the order.id
    params["service_info"]["estimate"] = JSON.parse(params["service_info"]["estimate"])
    @shipping_info = params
    if @shipping_info["service_info"]["service"].include?("UPS")
      shipping_array = @shipping_info["service_info"]["service"].split(" ")
      shipping_array.pop
      @shipping_price = (shipping_array.pop.to_f)/100
    else
      shipping_array = @shipping_info["service"].split(" ")
      @shipping_price = (shipping_array.pop.to_f)/100
    end
    @order_items = current_order.order_items
    @order_with_shipping = calc_order_total + @shipping_price
    if session[:order_id] == params[:id].to_i
      @order = Order.find(params[:id])
    else
      flash[:error] = "You do not have access to that order."

      redirect_to root_path
    end
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    @order.update(status: "complete")


    @order.order_items.each do |order_item|
      product = Product.find(order_item.product_id)
      previous_stock = product[:stock]
      ordered_stock = order_item.quantity

      new_stock = previous_stock.to_i - ordered_stock.to_i
      product.update(stock: new_stock)
    end

    session[:order_id] = nil # this clears the cart after you've checked out

    params["order"]["estimate"] = JSON.parse(params["order"]["estimate"])
    @shipping_details = params
    update_shipping = @shipping_details["order"]["estimate"]["service"].split(" ").pop
    update_shipping2 = update_shipping.to_f/100
    @order.update!(ship_price: update_shipping2)
    HTTParty.post("http://shipyostuff.herokuapp.com/save", :body => @shipping_details)
    # heroku url http://shipyostuff.herokuapp.com/save
    # localhost url http://localhost:3001/save

    redirect_to order_confirmation_path(params[:id])

  end

  def confirmation
    @order = Order.find(params[:id])
    @order_items = @order.order_items

    @customer_info = get_customer_info(@order)

  end

  def get_total(order_items)
    order_items.inject(0) do |sum, i|
      sum + i.revenue
    end
  end

  def get_customer_info(order)
    customer_info = []

    customer_info.push(order.name, order.email, order.street, order.city, order.state, order.zip)
  end

  def shipped?(order_items, bool)
    final_items = []
    order_items.each do |order_item|
      if order_item.shipped == bool
        final_items.push(order_item)
      end
    end
    return final_items
  end

  def count_items(order_items, bool)
    count = 0
    order_items.each do |order_item|
      if order_item.shipped == bool
        count += order_item.quantity
      end
    end
    return count
  end

  def find_relevant_order_items(orders, merchant_id)
    relevant_order_items = []
    orders.each do |order|
      all_order_items = order.order_items
      order_items = all_order_items.where(merchant_id: merchant_id)
      relevant_order_items.push(order_items)
    end
    return relevant_order_items.flatten
  end

  def find_orders_by_status(orders, bool, merchant_id)
    relevant_orders = []
    orders.each do |order|
      # order_items include order_items that don't belong to the merchant
      all_order_items = find_relevant_order_items([order], merchant_id)
      all_order_items.each do |order_item|
        if order_item.shipped == bool
          relevant_orders.push(order_item.order)
        end
      end
    end
    return relevant_orders.uniq
  end

  def revenue(order_items, bool)
    revenue = 0
    order_items.each do |order_item|
      if order_item.shipped == bool
        revenue += order_item.revenue
      end
    end
    return revenue
  end

############################################################
  private

  def order_params
    params.require(:order).permit(:status, :name, :email, :street, :city, :state, :zip, :credit_card, :exp_date, :cvv, :billing_zip)
  end

  def redacted_cc(credit_card)
    credit_card.chars.last(4).join
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
  def us_states
  [
    ['AK', 'AK'],
    ['AL', 'AL'],
    ['AR', 'AR'],
    ['AZ', 'AZ'],
    ['CA', 'CA'],
    ['CO', 'CO'],
    ['CT', 'CT'],
    ['DC', 'DC'],
    ['DE', 'DE'],
    ['FL', 'FL'],
    ['GA', 'GA'],
    ['HI', 'HI'],
    ['IA', 'IA'],
    ['ID', 'ID'],
    ['IL', 'IL'],
    ['IN', 'IN'],
    ['KS', 'KS'],
    ['KY', 'KY'],
    ['LA', 'LA'],
    ['MA', 'MA'],
    ['MD', 'MD'],
    ['ME', 'ME'],
    ['MI', 'MI'],
    ['MN', 'MN'],
    ['MO', 'MO'],
    ['MS', 'MS'],
    ['MT', 'MT'],
    ['NC', 'NC'],
    ['ND', 'ND'],
    ['NE', 'NE'],
    ['NH', 'NH'],
    ['NJ', 'NJ'],
    ['NM', 'NM'],
    ['NV', 'NV'],
    ['NY', 'NY'],
    ['OH', 'OH'],
    ['OK', 'OK'],
    ['OR', 'OR'],
    ['PA', 'PA'],
    ['RI', 'RI'],
    ['SC', 'SC'],
    ['SD', 'SD'],
    ['TN', 'TN'],
    ['TX', 'TX'],
    ['UT', 'UT'],
    ['VA', 'VA'],
    ['VT', 'VT'],
    ['WA', 'WA'],
    ['WI', 'WI'],
    ['WV', 'WV'],
    ['WY', 'WY']
  ]
  end
end

app/views/orders/_orders.html.erb
<h1>Merchant's Orders</h1>

<div class="row">
  <div class="col-md-6">
    <h3>Total Revenue: <%= number_to_currency(shipped_revenue + unshipped_revenue) %> </h3>
    <h4>Shipped: <%= number_to_currency(shipped_revenue)%></h4>
    <h4>Not Shipped: <%= number_to_currency(unshipped_revenue) %></h4>
  </div>
  <div class="col-md-6">
    <h3>Total Number of Order Items: <%= (shipped_count + unshipped_count) %></h3>
    <h4>Shipped: <%= shipped_count %></h4>
    <h4>Not Shipped: <%= unshipped_count %></h4>
  </div>
</div>

<h3>Orders</h3>
<ul class="nav nav-tabs">
  <% if request.path == merchant_orders_path(params[:merchant_id]) %>
    <li role="presentation" class="active">
  <% else %>
    <li role="presentation">
  <% end %>
    <%= link_to "All Orders", merchant_orders_path(params[:merchant_id]), class: "btn btn-default" %>
  </li>

  <% if request.path == orders_shipped_path(params[:merchant_id]) %>
    <li role="presentation" class="active">
  <% else %>
    <li role="presentation">
  <% end %>
    <%= link_to "Shipped Orders", orders_shipped_path(params[:merchant_id]), class: "btn btn-default" %>
  </li>

  <% if request.path == orders_unshipped_path(params[:merchant_id]) %>
    <li role="presentation" class="active">
  <% else %>
    <li role="presentation">
  <% end %>
    <%= link_to "Unshipped Orders", orders_unshipped_path(params[:merchant_id]), class: "btn btn-default" %>
  </li>
</ul>


<% orders.each do |order| %>
    <h4><strong><%= link_to "Order ##{order.id}", merchant_order_path(params[:merchant_id], order.id) %></strong></h4>
    <h6>Ordered on: <%= order.updated_at %></h6>

    <table class="table table-hover">
      <tr>
        <th>Product</th>
        <th>Quantity</th>
        <th>Unit Price</th>
        <th>Total Revenue</th>
        <th>Status</th>
        <th></th>
      </tr>
      <% total = 0 %>
      <% order_items.each do |order_item| %>
        <% if order_item.order == order %>
          <tr>
            <td class="col-sm-3"><%= link_to "#{order_item.product.name}", product_path(order_item.product_id) %></td>
            <td class="col-sm-1"><%= order_item.quantity %></td>
            <td class="col-sm-2"><%= number_to_currency(order_item.product.price) %></td>
            <td class="col-sm-2"><%= number_to_currency(order_item.revenue) %></td>
            <% total += order_item.revenue %>
            <td class="col-sm-2"><%= order_item.shipped ? "Shipped" : "Not Shipped" %></td>
            <td class="col-sm-2"> <%= order_item.shipped ? (" ") : (link_to "Shipped", mark_shipped_path(params[:merchant_id], order_item.id), method: :patch, class: "btn btn-success") %> </td>
          </tr>
        <% end %>
      <% end %>
      <tfoot>
        <tr>
          <td>TOTAL</td>
          <td></td>
          <td></td>
          <td><strong><%= number_to_currency(total) %></strong></td>
          <td></td>
          <td></td>
        </tr>
      </tfoot>
    </table>

<% end %>

app/views/orders/confirmation.html.erb
<h1>Order Confirmation</h1>

<h3>Below is your order confirmation</h3>

<p>Order placed: <%= @order.created_at %></p>

<h4>Payment Details</h4>
<div class="row">
  <div class="col-md-8 .col-md-offset-2">
    <table class="table">
      <tr>
        <td class="text-right">Status:</td>
        <td>To be shipped</td>
        <td class="text-right">Credit Card:</td>
        <td><%= @order.credit_card %></td>
      </tr>
      <tr>
        <td class="text-right">Name:</td>
        <td><%= @order.name %></td>
        <td class="text-right">Exp Date:</td>
        <td><%= @order.exp_date %></td>
      </tr>
      <tr>
        <td class="text-right">Email:</td>
        <td><%= @order.email %></td>
        <td class="text-right">CCV Code:</td>
        <td><%= @order.cvv %></td>
      </tr>
      <tr>
        <td class="text-right">Address:</td>
        <td><%= @order.street %> <%= @order.city %>, <%= @order.state %> <%= @order.zip %></td>
        <td class="text-right">Billing Zip:</td>
        <td><%= @order.billing_zip %></td>
      </tr>
    </table>
  </div>
</div>

<h4>Order Details</h4>
<div class="row">
  <div class="col-md-10 .col-md-offset-1">
    <table class="table">
      <tr>
        <th>Product</th>
        <th>Quantity</th>
        <th>Unit Price</th>
        <th>Total Price</th>
        <th>Status</th>
      </tr>
      <% total = 0 %>
      <% @order_items.each do |order_item| %>
        <% if order_item.order_id == @order.id %>
          <tr>
            <td class="col-sm-4"><%= link_to "#{order_item.product.name}", product_path(order_item.product.id) %></td>
            <td class="col-sm-1"><%= order_item.quantity %></td>
            <td class="col-sm-2"><%= number_to_currency(order_item.product.price) %></td>
            <td class="col-sm-2"><%= number_to_currency(order_item.revenue) %></td>
            <% total += order_item.revenue %>
            <td class="col-sm-3"><%= order_item.shipped ? "Shipped" : "Not Shipped" %></td>
          </tr>
        <% end %>
      <% end %>
      <tfoot>
        <tr>
          <td>TOTAL WITH SHIPPING</td>
          <td></td>
          <td></td>
          <td><strong>$<%= @order.ship_price + total %></strong></td>
          <td></td>

        </tr>
      </tfoot>
    </table>
  </div>
</div>
<%= link_to "More Shopping", root_path %>

app/views/orders/edit.html.erb
<h1>Add Payment Details</h1>

<h3><%= @unit_total %> <%= @unit_total == 1 ? "Item" : "Items" %> in Your Cart</h3>


<% if @order_items.count == 0 %>
  <p class="text-center">
    There are no items in your shopping cart.  Please <%= link_to "go back", root_path %> and add some items to your cart.
  </p>
<% else %>
  <div class="row">
    <table class="table">
      <tr>
        <th></th>
        <th></th>
        <th></th>
        <th>Name</th>
        <th>Total</th>
      </tr>
      <% @order_items.each do |item| %>
        <tr>
          <td></td>
          <td></td>
          <td><%= image_tag(item.product.photo_url, class: "cart-thumbnail") %></td>

          <td><%= link_to "#{item.product.name}", merchant_product_path(merchant_id: item.product.merchant_id, id: item.product.id) %></td>
          <td><%= number_to_currency(item.revenue) %></td>
        </tr>
      <% end %>
      <tr>
          <td></td>
          <td></td>
          <td></td>
          <td>Shipping & Handling</td>
          <td>$<%= @shipping_price %></td>
      </tr>
      <tr>
        <td></td>
        <td></td>
        <td></td>
        <td><strong>Total: </strong></td>
        <td><strong>$<%= @order_with_shipping %></strong></td>
      </tr>
    </table>
  </div>
<% end %>


<%= bootstrap_form_for @order, url: order_path(params[:id]), :html => {:class => 'form-horizontal'} do |f| %>
<fieldset>
  <legend>Payment Details</legend>
    <div class="col-md-8">
      <%= f.text_field :credit_card %>
    </div>
    <div class="col-md-8">
      <%= f.text_field :exp_date %>
    </div>
    <div class="col-md-8">
      <%= f.text_field :cvv %>
    </div>
    <div class="col-md-8">
      <%= f.text_field :billing_zip %>
    </div>
      <%= f.hidden_field :estimate, :value => @shipping_info.to_json %>
      <%= f.hidden_field :order, :value => @order_with_shipping %>
 </fieldset>

  <%= f.submit 'Place Order', :data => {:confirm => 'Place Order Now?'}, class: 'btn btn-primary' %>
<% end %>

app/views/orders/estimate.html.erb
<h3><%= @unit_total %> <%= @unit_total == 1 ? "Item" : "Items" %> in Your Cart</h3>


<% if @order_items.count == 0 %>
  <p class="text-center">
    There are no items in your shopping cart.  Please <%= link_to "go back", root_path %> and add some items to your cart.
  </p>
<% else %>
  <div class="row">
    <table class="table">
      <tr>
        <th></th>
        <th></th>
        <th></th>
        <th>Name</th>
        <th>Total</th>
      </tr>
      <% @order_items.each do |item| %>
        <tr>
          <td></td>
          <td></td>
          <td><%= image_tag(item.product.photo_url, class: "cart-thumbnail") %></td>

          <td><%= link_to "#{item.product.name}", merchant_product_path(merchant_id: item.product.merchant_id, id: item.product.id) %></td>

          <td><%= number_to_currency(item.revenue) %></td>
        </tr>
      <% end %>
      <tr>
        <td></td>
        <td></td>
        <td></td>
        <td><strong>Total before shipping: </strong></td>
        <td><strong><%= number_to_currency(@order_total) %></strong></td>
      </tr>
    </table>
  </div>
<% end %>


<h1>Get Shipping Estimate</h1>

<%= bootstrap_form_for :estimate, url: results_path, class: 'form-horizontal' do |f| %>
<fieldset>
  <legend>Shipping Details</legend>
    <div class="col-md-8">
      <%= f.text_field :name %>
    </div>
    <div class="col-md-8">
      <%= f.text_field :email %>
    </div>
    <div class="col-md-8">
      <%= f.text_field :street %>
    </div>
    <div class="col-md-8">
      <%= f.text_field :city %>
    </div>
    <div class="col-md-8">
      <%= f.select :state, options_for_select(us_states),
                  class: 'form-control' %>
    </div>
    <div class="col-md-8">
      <%= f.text_field :zip %>
    </div>
      <%= f.hidden_field :country, :value => 'US' %>
      <%= f.hidden_field :box_size, :value => @package_size %>
      <%= f.hidden_field :total_weight, :value => @total_weight %>
 </fieldset>

  <%= f.submit 'Get Estimate', class: 'btn btn-primary' %>
<% end %>

app/views/orders/index.html.erb
<%= render :partial => 'orders',
           :locals => { :merchant          => @merchant,
                        :order_items       => @order_items,
                        :orders            => @orders,
                        :shipped_revenue   => @shipped_revenue,
                        :unshipped_revenue => @unshipped_revenue,
                        :shipped_count     => @shipped_count,
                        :unshipped_count   => @unshipped_count } %>

app/views/orders/results.html.erb
<h3><%= @unit_total %> <%= @unit_total == 1 ? "Item" : "Items" %> in Your Cart</h3>

<% if @order_items.count == 0 %>
  <p class="text-center">
    There are no items in your shopping cart.  Please <%= link_to "go back", root_path %> and add some items to your cart.
  </p>
<% else %>
  <div class="row">
    <table class="table">
      <tr>
        <th></th>
        <th></th>
        <th></th>
        <th>Name</th>
        <th>Total</th>
      </tr>
      <% @order_items.each do |item| %>
        <tr>
          <td></td>
          <td></td>
          <td><%= image_tag(item.product.photo_url, class: "cart-thumbnail") %></td>

          <td><%= link_to "#{item.product.name}", merchant_product_path(merchant_id: item.product.merchant_id, id: item.product.id) %></td>

          <td><%= number_to_currency(item.revenue) %></td>
        </tr>
      <% end %>
      <tr>
        <td></td>
        <td></td>
        <td></td>
        <td><strong>Total before shipping: </strong></td>
        <td><strong><%= number_to_currency(@order_total) %></strong></td>
      </tr>
    </table>
  </div>
<% end %>


<%= form_for :service_info, url: create_estimate_path do |f|  %>
<div class="col-sm-3">
  <h3 class="primo">UPS</h3>
  <table class ="table table-border">
    <thead>
      <th>
        Service
      </th>
      <th>
        Price
      </th>
      <th>
        Estimated Delivery
      </th>
      <tbody>
        <% @ups.each do |rate| %>
        <tr>
          <td>
            <%= rate[0] %>
          </td>
          <td>
            $<%= rate[1].to_f/100 %>
          </td>
          <td>
            <% if rate[2] %>
            <%= DateTime.parse(rate[2]).strftime('%D') %>
            <% else %>
            Not available
            <% end %>
          </td>
          <td>
            <%= f.radio_button :service, rate %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </thead>
  </table>
</div>

<div class="col-sm-3">
  <h3 class="primo">USPS</h3>
  <table class ="table table-border">
    <thead>
      <th>
        Service
      </th>
      <th>
        Price
      </th>
      <tbody>
        <% @usps.each do |rate| %>
        <tr>
          <td>
            <%= rate[0] %>
          </td>
          <td>
            $<%= rate[1].to_f/100 %>
          </td>
          <td>
            <%= radio_button_tag :service, rate %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </thead>
  </table>
</div>
<br>
<%= f.hidden_field :estimate, :value => @estimate.to_json %>

<%= f.submit 'Continue to Payment', class: 'btn btn-primary below' %>
<% end %>

app/views/orders/shipped.html.erb
<%= render :partial => 'orders',
           :locals => { :merchant          => @merchant,
                        :order_items       => @order_items_shipped,
                        :orders            => @shipped_orders,
                        :shipped_revenue   => @shipped_revenue,
                        :unshipped_revenue => @unshipped_revenue,
                        :shipped_count     => @shipped_count,
                        :unshipped_count   => @unshipped_count } %>

app/views/orders/show.html.erb
<h1>Order #<%= @order.id %> Details</h1>

<h3>Payment Details</h3>
<div class="row">
  <div class="col-md-8 .col-md-offset-2">
    <table class="table">
      <tr>
        <td class="text-right">Status:</td>
        <td><%= @order.status %></td>
        <td class="text-right">Credit Card:</td>
        <td>XXXX-XXXX-XXXX-<%= @redacted_cc %></td>
      </tr>
      <tr>
        <td class="text-right">Name:</td>
        <td><%= @order.name %></td>
        <td class="text-right">Exp Date:</td>
        <td><%= @order.exp_date %></td>
      </tr>
      <tr>
        <td class="text-right">Email:</td>
        <td><%= @order.email %></td>
        <td class="text-right">CCV Code:</td>
        <td><%= @order.cvv %></td>
      </tr>
      <tr>
        <td class="text-right">Address:</td>
        <td><%= @order.street %> <%= @order.city %>,<%= @order.state %> <%= @order.zip %></td>
        <td class="text-right">Billing Zip:</td>
        <td><%= @order.billing_zip %></td>
      </tr>
    </table>
  </div>
</div>

<h3>Order Details</h3>
<div class="row">
  <div class="col-md-10 .col-md-offset-1">
    <table class="table">
      <tr>
        <th>Product</th>
        <th>Quantity</th>
        <th>Unit Price</th>
        <th>Total Revenue</th>
        <th>Status</th>
      </tr>
      <% total = 0 %>
      <% @order_items.each do |order_item| %>
        <% if order_item.order_id == @order.id %>
          <tr>
            <td class="col-sm-4"><%= order_item.product.name %></td>
            <td class="col-sm-1"><%= order_item.quantity %></td>
            <td class="col-sm-2"><%= number_to_currency(order_item.product.price) %></td>
            <td class="col-sm-2"><%= number_to_currency(order_item.revenue) %></td>
            <% total += order_item.revenue %>
            <td class="col-sm-3"><%= order_item.shipped ? "Shipped" : "Not Shipped" %></td>
          </tr>
        <% end %>
      <% end %>
      <tfoot>
        <tr>
          <td>TOTAL</td>
          <td></td>
          <td></td>
          <td><strong><%= number_to_currency(total) %></strong></td>
          <td></td>
        </tr>
      </tfoot>
    </table>
  </div>
</div>

app/views/orders/unshipped.html.erb
<%= render :partial => 'orders',
           :locals => { :merchant          => @merchant,
                        :order_items       => @order_items_unshipped,
                        :orders            => @unshipped_orders,
                        :shipped_revenue   => @shipped_revenue,
                        :unshipped_revenue => @unshipped_revenue,
                        :shipped_count     => @shipped_count,
                        :unshipped_count   => @unshipped_count } %>