config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :products do
    resources :reviews, only: [:new, :create]
  end

  get '/login'  =>  'sessions#new', as: 'login'
  post '/login' =>  'sessions#create'
  delete '/logout' => 'sessions#destroy', as: 'logout'
  resources :merchants, only: [:new, :create, :show] do
    get :dashboard
    resources :products
    resources :orders, only: [:index, :show]

  end

  resources :categories, only: [:new, :create, :show]

  resources :orders, only: [:edit, :update, :show]

  get 'orders/:id/estimate', to: 'orders#estimate', as: "estimate"
  post 'orders/:id/results', to: 'orders#results', as: "results"
  post 'orders/:id/create-estimate', to:'orders#create_estimate', as: 'create-estimate'
  get 'orders/:id/confirmation', to: 'orders#confirmation', as: 'order_confirmation'
  get 'merchant/:merchant_id/orders/shipped' => 'orders#shipped', as: "orders_shipped"
  get 'merchant/:merchant_id/orders/unshipped' => 'orders#unshipped', as: "orders_unshipped"

  patch 'merchants/:merchant_id/products/:id/active_update' => 'products#active_update', as: "active_update"

  patch 'merchants/:merchant_id/order_items/:id' => 'order_items#mark_shipped', as: "mark_shipped"

  get '/cart'             =>  'carts#show'
  post '/add_to_cart/:id' =>  'carts#add_to_cart', as: 'add_to_cart'

  resources :order_items

end

app/models/merchant.rb
class Merchant < ActiveRecord::Base
  # Validations
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true, format: {with: /@/}
  validates :password, presence: true
  validates :password_confirmation, presence: true

  # Associations
  has_secure_password

  has_many :products
  has_many :orders, :through => :order_items
  has_many :order_items

  # Scopes

  #Merchant.find(1).shipped(true/false) returns all shipped order items
  def shipped?(boolean)
    order_items.where(shipped: boolean)
  end
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  before_action :require_login, only: [:dashboard]

  def show
    @merchant = Merchant.find(params[:id])

    @merchant_products = @merchant.products.where(active: true)

    render :show
  end

  def new
    @merchant = Merchant.new
  end

  def create
    @merchant = Merchant.create(merchant_params)

    if @merchant.save
      session[:merchant_id] = @merchant.id
      redirect_to root_path
    else
      flash.now[:error] = "Try again, account was not created."
      render :new
    end
  end

  def dashboard
    if session[:merchant_id] == params[:merchant_id].to_i
    # may change the params depending on sessions
      @merchant = Merchant.find(params[:merchant_id])

      @products = @merchant.products

      @order_items = @merchant.order_items

      @revenue = 0

      @order_items.each do |order_item|
        @revenue += order_item.revenue
      end

     else
      flash[:error] = "You do not have access to that merchant's dashboard"

      redirect_to merchant_dashboard_path(session[:merchant_id])
    end
  end

#________________________________________________________________________________
  private

  def merchant_params
    params.require(:merchant).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/views/merchants/dashboard.html.erb
<h3>Merchant Dashboard</h3>

<div class="merch-dash-tools row">
  <div class="col-md-3">
    <h5><%= link_to "Add Product", new_merchant_product_path(params[:merchant_id]), class: "btn btn-primary" %></h5>
    <h5><%= link_to "Add Category", new_category_path, class: "btn btn-primary" %></h5>
  </div>
  <div class="col-md-3 col-md-offset-6">
    <div>
      <h5><%= link_to "Orders", merchant_orders_path(params[:merchant_id]), class: "btn btn-primary" %></h5>
    </div>
    <div>
      <h4>Revenue: <%= number_to_currency(@revenue) %></h4>
    </div>
  </div>
</div>

<h4>Products</h4>
  <table class="table">
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.name, product_path(product.id) %></td>
        <td><%= product.active ? "ACTIVE" : "INACTIVE" %></td>
        <td><%= link_to "Edit", edit_merchant_product_path(product.merchant_id, product.id), class: "btn btn-default" %></td>
        <td><%= link_to "Change status", product_path(product.id), method: :patch, class: "btn btn-default" %></td>
        <td><%= link_to "X", merchant_product_path(product.merchant_id, product.id), method: :delete, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </table>

app/views/merchants/new.html.erb
<div class="row">
  <div class="login-form col-md-4 col-md-offset-4">


    <h3>Sign Up!</h3>

    <% if @merchant.errors.any? %>
      <div>
        <%= @merchant.errors.full_messages.first %>
      </div>
      <br>
    <% end %>

    <%= form_for @merchant do |f| %>

      <fieldset>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
      </fieldset>

      <%= f.submit "Create Account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/merchants/show.html.erb
<h1><%= @merchant.name %></h1>

<% @merchant_products.each do |product| %>
  <div class="col-md-4">
    <ul style="list-style: none;">
      <li><div class="product-image thumbnail"><%= image_tag(product.photo_url) %></div></li>
      <li><h3><%= link_to product.name, product_path(product.id) %></h3></li>
      <li><h5><%= number_to_currency(product.price) %> each</h5></li>
      <li><h5>Available: <%= product.stock %></h5></li>
    </ul>
  </div>
<% end %>