config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :products do
    resources :reviews, only: [:new, :create]
  end

  get '/login'  =>  'sessions#new', as: 'login'
  post '/login' =>  'sessions#create'
  delete '/logout' => 'sessions#destroy', as: 'logout'
  resources :merchants, only: [:new, :create, :show] do
    get :dashboard
    resources :products
    resources :orders, only: [:index, :show]

  end

  resources :categories, only: [:new, :create, :show]

  resources :orders, only: [:edit, :update, :show]

  get 'orders/:id/estimate', to: 'orders#estimate', as: "estimate"
  post 'orders/:id/results', to: 'orders#results', as: "results"
  post 'orders/:id/create-estimate', to:'orders#create_estimate', as: 'create-estimate'
  get 'orders/:id/confirmation', to: 'orders#confirmation', as: 'order_confirmation'
  get 'merchant/:merchant_id/orders/shipped' => 'orders#shipped', as: "orders_shipped"
  get 'merchant/:merchant_id/orders/unshipped' => 'orders#unshipped', as: "orders_unshipped"

  patch 'merchants/:merchant_id/products/:id/active_update' => 'products#active_update', as: "active_update"

  patch 'merchants/:merchant_id/order_items/:id' => 'order_items#mark_shipped', as: "mark_shipped"

  get '/cart'             =>  'carts#show'
  post '/add_to_cart/:id' =>  'carts#add_to_cart', as: 'add_to_cart'

  resources :order_items

end

app/models/product.rb
class Product < ActiveRecord::Base
  # Validations
  validates :name, presence: true, uniqueness: true
  validates :price, presence: true
  validates_numericality_of :price, :greater_than => 0

  # Associations
  belongs_to :merchant
  has_many :order_items
  has_many :reviews
  has_and_belongs_to_many :categories
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :require_login, except: [:index, :show]
  before_action :check_product_active_status, only: [:show]

  def index
    # a guest or merchant can view all products with their details
    # @products = Product.all
    @products = Product.where(active: true)

    @order_item = current_order.order_items.new
    # a guest or merchant can view all products by category
  end

  def show
    # product detail page
    # some conditional visuals based on if you're logged in or not (view-things)
      # merchants can't buy their own products (i.e. no 'add to cart' button for them)
      # merchants can't leave reviews for their own products
      # if instock? == false, you can't add it to the cart
    @product = Product.find(params[:id])
    @order_item = current_order.order_items.new
    @review = Review.new

    @reviews = @product.reviews

    @average = average_rating(@reviews)

    existing_cart_product = current_order.order_items.select {|item| item.product_id == @product.id }

    if existing_cart_product.length == 0
      @additional_stock_available = @product.stock.to_i
    elsif existing_cart_product.length > 0
      calc_additional_stock_available(existing_cart_product[0])
    end
  end

  def calc_additional_stock_available(existing_cart_product)
    cart_product_units = existing_cart_product.quantity
    @additional_stock_available = @product.stock.to_i - cart_product_units.to_i

    return @additional_stock_available
  end

  def new
    # a merchant can create a new product using a form
    # (nested routing bc the prod is associated with that merchant only)
    # takes you to a form page
    if session[:merchant_id] == params[:merchant_id].to_i
      @product = Product.new

      @categories = Category.all.order(:name)
    else
      flash[:error] = "You do not have access to that merchant's products"

      redirect_to merchant_dashboard_path(session[:merchant_id])
    end
  end

  def create
    # submits the form to save the new product to the db
    # redirects you to the merchant dashboard page
    @product = Product.create(product_params)

    if @product.save
      categories_update(@product)

      if params[:review]
        @review = Review.create(review_params)
      end
      redirect_to merchant_dashboard_path(params[:merchant_id])
    else
      flash[:error] = "Please enter valid values"
      redirect_to :back
    end
  end

  def edit
    # a merchant can edit details about a product using a form
    # note: changing the price of a product will NOT change the price of the order_item (intentionally)
    # takes you to a form page
    if session[:merchant_id] == params[:merchant_id].to_i
      @product = Product.find(params[:id])

      @categories = Category.all.order(:name)
    else
      flash[:error] = "You do not have access to that merchant's products"

      redirect_to merchant_dashboard_path(session[:merchant_id])
    end
  end

  def update
    # submits the form to save changes to the product details
    # redirects you to the merchant dashboard page
    @product = Product.find(params[:id])

    if params[:merchant_id]
      @product.update(product_params)

      categories_update(@product)

      redirect_to merchant_dashboard_path(params[:merchant_id])
    else
      active_update(@product)

      redirect_to(:back)
    end

  end

  def destroy
    # a merchant can delete a product from their dashboard page by clicking the 'x' next to the product
    # does it right on the same screen, doesn't take you somewhere else to do it
    # redirects you to the merchant dashboard page when done
    @product = Product.find(params[:id])

    @product.destroy

    redirect_to(:back)
  end

  def categories_update(product)
    product.categories.destroy_all

    input_categories = params[:product][:categories]

    input_categories.each do |input|
      if input != ""
        product.categories << Category.find(input)
      end
    end
  end

  def active_update(product)
    product.active ? product.update(active: false) : product.update(active: true)
  end

  def average_rating(reviews)
    reviews.inject(0) { |sum, r| sum + r.rating}.to_f / reviews.size
  end

#--------------------------------------------------------------------------------
  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :stock, :active, :photo_url, :merchant_id, :categories)
  end

  def review_params
    params.require(:review).permit(:content, :rating, :product_id)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<div class="col-md-8">
  <%= form_for @product, url: merchant_product_path(params[:merchant_id], params[:id]), class: 'form' do |f| %>
    <fieldset>
      <legend>Product Details</legend>

        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :price %>
          <%= f.text_field :price, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :stock %>
          <%= f.number_field :stock, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :active %>
          <%= f.select :active, [['Active', true], ['Inactive', false]], class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :photo_url %>
          <%= f.text_field :photo_url, class: "form-control" %>
        </div>

        <%= f.hidden_field :merchant_id, :value => params[:merchant_id] %>

        <div class="form-group">
          <%= f.label :categories %>
          <%= f.collection_check_boxes( :categories, @categories, :id, :name, checked: @product.categories.map(&:id), class: "form-control") %>
        </div>
    </fieldset>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>
</div>

app/views/products/index.html.erb
<%= render partial: "shared/category_product_index",
          :locals => { :header          => "All Products" } %>

app/views/products/new.html.erb
<h1>Add New Product</h1>

<%= bootstrap_form_for @product, url: merchant_products_path(params[:merchant_id]) do |f| %>
  <fieldset>
    <legend>Product Details</legend>
      <%= f.text_field :name %>

      <%= f.text_area :description %>

      <%= f.text_field :price %>

      <%= f.number_field :stock %>

      <%= f.select :active, [['Active', true], ['Inactive', false]] %>

      <%= f.text_field :photo_url %>

      <%= f.collection_check_boxes( :categories, @categories, :id, :name ) %>

      <%= f.hidden_field :merchant_id, :value => params[:merchant_id] %>
  </fieldset>

  <%= f.submit %>
<% end %>

app/views/products/show.html.erb
<h3><%= @product.name %></h3>
<h5><%= link_to @product.merchant.name, merchant_path(id: @product.merchant.id) %></h5>

<div class="row">
  <div class="col-md-6">
    <%= image_tag(@product.photo_url) %>
  </div>
  <div class="col-md-6">
    <dl class="dl-horizontal">
      <dt>Price: </dt>
      <dd><%= number_to_currency(@product.price) %></dd>
      <dt>Number Instock: </dt>
      <dd><%= @product.stock %></dd>
      <dt>Description: </dt>
      <dd><%= @product.description %></dd>
    </dl>
    <div class="col-md-4 col-md-offset-8">
      <%= form_for @order_item do |f| %>
          <div class="input-group">
            <%= f.number_field :quantity, value: 1, class: "form-control", min: 1, max: @additional_stock_available %>
            <div class="input-group-btn">
              <%= f.hidden_field :product_id, value: @product.id %>
              <%= f.hidden_field :merchant_id, value: @product.merchant_id %>
              <%= f.hidden_field :shipped, value: false %>
              <%= f.hidden_field :revenue, value: @product.price %>
              <%= f.submit "Add to Cart", class: "btn btn-primary" %>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>
<% unless @reviews.blank? %>

  <h5><%= "Average rating for this product is #{@average} " %></h5>
<% else %>

  <h5>Leave the first review for this product!</h5>

<% end %>

<% unless session[:merchant_id] == @product.merchant_id %>
  <div class="row">
    <table class="table">
      <tr>
        <th>Reviews</th>
        <th>Ratings
        <% unless @reviews.blank? %>
          <%= "(average = #{@average})" %>
          <% end %>
        </th>
      </tr>

      <% @reviews.each do |review| %>
      <tr>
        <td><%= review.content %></td>
        <td><%= review.rating %></td>
      </tr>
      <% end %>
    </table>
  </div>

  <h4>Want to Review this Product?</h4>

  <%= bootstrap_form_for @review, url: product_reviews_path(params[:id]) do |f| %>

    <fieldset>
      <h4>Rating <small>rate this product on a scale from 1 - 5 </small></h4>
      <%= f.label "1" %>
      <%= f.radio_button :rating, 1, inline: true %>

      <%= f.label "2" %>
      <%= f.radio_button :rating, 2, inline: true %>

      <%= f.label "3" %>
      <%= f.radio_button :rating, 3, inline: true %>

      <%= f.label "4" %>
      <%= f.radio_button :rating, 4, inline: true %>

      <%= f.label "5" %>
      <%= f.radio_button :rating, 5, inline: true %>

      <%= f.text_area :content %>

      <%= f.hidden_field :product_id, :value => params[:id] %>
    </fieldset>

    <%= f.submit "Add this Review" %>
  <% end %>

<% end %>