config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :products do
    resources :reviews, only: [:new, :create]
  end

  get '/login'  =>  'sessions#new', as: 'login'
  post '/login' =>  'sessions#create'
  delete '/logout' => 'sessions#destroy', as: 'logout'
  resources :merchants, only: [:new, :create, :show] do
    get :dashboard
    resources :products
    resources :orders, only: [:index, :show]

  end

  resources :categories, only: [:new, :create, :show]

  resources :orders, only: [:edit, :update, :show]

  get 'orders/:id/estimate', to: 'orders#estimate', as: "estimate"
  post 'orders/:id/results', to: 'orders#results', as: "results"
  post 'orders/:id/create-estimate', to:'orders#create_estimate', as: 'create-estimate'
  get 'orders/:id/confirmation', to: 'orders#confirmation', as: 'order_confirmation'
  get 'merchant/:merchant_id/orders/shipped' => 'orders#shipped', as: "orders_shipped"
  get 'merchant/:merchant_id/orders/unshipped' => 'orders#unshipped', as: "orders_unshipped"

  patch 'merchants/:merchant_id/products/:id/active_update' => 'products#active_update', as: "active_update"

  patch 'merchants/:merchant_id/order_items/:id' => 'order_items#mark_shipped', as: "mark_shipped"

  get '/cart'             =>  'carts#show'
  post '/add_to_cart/:id' =>  'carts#add_to_cart', as: 'add_to_cart'

  resources :order_items

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :products

end

app/models/estimate.rb
class Estimate < ActiveRecord::Base
end

app/models/merchant.rb
class Merchant < ActiveRecord::Base
  # Validations
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true, format: {with: /@/}
  validates :password, presence: true
  validates :password_confirmation, presence: true

  # Associations
  has_secure_password

  has_many :products
  has_many :orders, :through => :order_items
  has_many :order_items

  # Scopes

  #Merchant.find(1).shipped(true/false) returns all shipped order items
  def shipped?(boolean)
    order_items.where(shipped: boolean)
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  # Associations
  has_many :order_items
  has_many :products, :through => :order_items
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  # Validations
  validates :product_id, presence: true
  validates :order_id, presence: true
  validates :revenue, presence: true
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }

  # Associations
  belongs_to :order
  belongs_to :product
  belongs_to :merchant

end

app/models/product.rb
class Product < ActiveRecord::Base
  # Validations
  validates :name, presence: true, uniqueness: true
  validates :price, presence: true
  validates_numericality_of :price, :greater_than => 0

  # Associations
  belongs_to :merchant
  has_many :order_items
  has_many :reviews
  has_and_belongs_to_many :categories
end

app/models/review.rb
class Review < ActiveRecord::Base
  # Validations
  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true }
  validates :product_id, presence: true

  # Associations
  belongs_to :product
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @active_products = Product.where(active: true)
    @product_first_row = @active_products.first(3)
    @product_second_row = @active_products.last(3)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  def us_states
  [
    ['AK', 'AK'],
    ['AL', 'AL'],
    ['AR', 'AR'],
    ['AZ', 'AZ'],
    ['CA', 'CA'],
    ['CO', 'CO'],
    ['CT', 'CT'],
    ['DC', 'DC'],
    ['DE', 'DE'],
    ['FL', 'FL'],
    ['GA', 'GA'],
    ['HI', 'HI'],
    ['IA', 'IA'],
    ['ID', 'ID'],
    ['IL', 'IL'],
    ['IN', 'IN'],
    ['KS', 'KS'],
    ['KY', 'KY'],
    ['LA', 'LA'],
    ['MA', 'MA'],
    ['MD', 'MD'],
    ['ME', 'ME'],
    ['MI', 'MI'],
    ['MN', 'MN'],
    ['MO', 'MO'],
    ['MS', 'MS'],
    ['MT', 'MT'],
    ['NC', 'NC'],
    ['ND', 'ND'],
    ['NE', 'NE'],
    ['NH', 'NH'],
    ['NJ', 'NJ'],
    ['NM', 'NM'],
    ['NV', 'NV'],
    ['NY', 'NY'],
    ['OH', 'OH'],
    ['OK', 'OK'],
    ['OR', 'OR'],
    ['PA', 'PA'],
    ['RI', 'RI'],
    ['SC', 'SC'],
    ['SD', 'SD'],
    ['TN', 'TN'],
    ['TX', 'TX'],
    ['UT', 'UT'],
    ['VA', 'VA'],
    ['VT', 'VT'],
    ['WA', 'WA'],
    ['WI', 'WI'],
    ['WV', 'WV'],
    ['WY', 'WY']
  ]
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Primo!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <link rel="icon" type="image/jpg" href="scrunchie.jpg" sizes="16x16">
</head>
<div class="container-fluid">
  <body>

    <header>
      <% if flash[:error] %>
        <div class="alert alert-danger" role="alert">
          <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
          <%= flash[:error] %>
        </div>
      <% end %>
      <div class="row">
        <div class="col-md-8 col-sm-8 col-md-offset-2 col-sm-offset-2">
          <div class="logo">
            <%= image_tag("primo_logo.jpg", :class => "img_preview") %>
          </div>
        </div>
      </div>

      <% if session[:merchant_id] %>
        <div class="account-buttons">
          <%= link_to "Logout", logout_path , method: :delete, class: "btn btn-default pull-right" %>
        </div>

      <% else %>

        <div class="account-buttons">
          <%= link_to "Login", login_path, class: "btn btn-default pull-right" %>
          <%= link_to "Sign Up!", new_merchant_path, class: "btn btn-default pull-right" %>
        </div>
      <% end %>
    </header>


    <nav class="navbar navbar-default">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">

          <a class="navbar-brand" href="/"><span class="glyphicon glyphicon-star" aria-hidden="true"></span></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Shop <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "All Products", products_path %></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">By Category</li>
                <% @categories.each do |category| %>
                  <% if category.products.size != 0 %>
                  <li><%= link_to "#{category.name}", category_path(category.id) %></li>
                  <% end %>
                <% end %>
              </ul>
            </li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <% if session[:merchant_id] %>
              <li><%= link_to "Merchant Dashboard", merchant_dashboard_path(session[:merchant_id]) %></li>
            <% end %>
              <li><p class="navbar-text">Welcome, <%= @merchant_name %></p></li>
              <li><a href= "/cart"><i class="fa fa-shopping-cart"></i> (<%= cart_units %>)</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->

    </nav>

    <%= yield %>

  </body>
</div>
</html>

app/views/shared/_category_product_index.html.erb
<h3><%= header %></h3>

<% @products.each do |product| %>
  <div class="col-md-4">
    <ul style="list-style: none;">
      <li><div class="product-image thumbnail"><%= image_tag(product.photo_url) %></div></li>
      <li><h3><%= link_to product.name, product_path(product.id) %></h3></li>
      <li><h5><%= number_to_currency(product.price) %> each</h5></li>
      <li><h5>Available: <%= product.stock %></h5></li>
    </ul>
  </div>
<% end %>